/**
 * PTE Speaking - EXPANDED Question Bank Part 2
 * Answer Short Question (200), Summarize Group Discussion (15), Respond to Situation (20)
 * Auto-merges into PTE.Questions on load
 */
window.PTE = window.PTE || {};
window.PTE._bankVocab = {

'answer-short-question': [
{id:'xasq-1',text:'What do you call a person who studies rocks and minerals?',answer:'geologist',keywords:['geologist']},
{id:'xasq-2',text:'What is the main gas in the Earth\'s atmosphere?',answer:'nitrogen',keywords:['nitrogen']},
{id:'xasq-3',text:'What do you call the fear of heights?',answer:'acrophobia',keywords:['acrophobia','vertigo']},
{id:'xasq-4',text:'What instrument measures atmospheric pressure?',answer:'barometer',keywords:['barometer']},
{id:'xasq-5',text:'Which continent is the Sahara Desert located in?',answer:'Africa',keywords:['africa']},
{id:'xasq-6',text:'What do you call a person who writes novels?',answer:'novelist',keywords:['novelist','author','writer']},
{id:'xasq-7',text:'What is the smallest prime number?',answer:'two',keywords:['two','2']},
{id:'xasq-8',text:'What do you call a baby cat?',answer:'kitten',keywords:['kitten']},
{id:'xasq-9',text:'What is the chemical symbol for iron?',answer:'Fe',keywords:['fe','iron']},
{id:'xasq-10',text:'How many continents are there in the world?',answer:'seven',keywords:['seven','7']},
{id:'xasq-11',text:'What do you call the study of fossils?',answer:'paleontology',keywords:['paleontology','palaeontology']},
{id:'xasq-12',text:'What is the capital of Canada?',answer:'Ottawa',keywords:['ottawa']},
{id:'xasq-13',text:'What do you call a person who studies insects?',answer:'entomologist',keywords:['entomologist']},
{id:'xasq-14',text:'What language has the most native speakers in the world?',answer:'Mandarin',keywords:['mandarin','chinese']},
{id:'xasq-15',text:'What do you call the study of the universe?',answer:'cosmology',keywords:['cosmology','astronomy']},
{id:'xasq-16',text:'What is the tallest mountain in the world?',answer:'Mount Everest',keywords:['mount everest','everest']},
{id:'xasq-17',text:'What do you call a person who studies the ocean?',answer:'oceanographer',keywords:['oceanographer','marine biologist']},
{id:'xasq-18',text:'What is the longest river in the world?',answer:'Nile',keywords:['nile']},
{id:'xasq-19',text:'What do you call the document that proves your identity?',answer:'identification',keywords:['identification','id','identity card']},
{id:'xasq-20',text:'What is the opposite of expand?',answer:'contract',keywords:['contract','shrink']},
{id:'xasq-21',text:'What do you call someone who cannot see?',answer:'blind',keywords:['blind']},
{id:'xasq-22',text:'How many strings does a standard guitar have?',answer:'six',keywords:['six','6']},
{id:'xasq-23',text:'What is the currency of the United Kingdom?',answer:'pound',keywords:['pound','sterling']},
{id:'xasq-24',text:'What do you call a shape with five sides?',answer:'pentagon',keywords:['pentagon']},
{id:'xasq-25',text:'What is the largest country in the world by area?',answer:'Russia',keywords:['russia']},
{id:'xasq-26',text:'What do you call a story based on someone\'s life written by another person?',answer:'biography',keywords:['biography']},
{id:'xasq-27',text:'What is the process of water changing from liquid to solid called?',answer:'freezing',keywords:['freezing','solidification']},
{id:'xasq-28',text:'What do you call the person who leads an orchestra?',answer:'conductor',keywords:['conductor']},
{id:'xasq-29',text:'What is the national language of Egypt?',answer:'Arabic',keywords:['arabic']},
{id:'xasq-30',text:'What do you call a scientist who studies volcanoes?',answer:'volcanologist',keywords:['volcanologist']},
{id:'xasq-31',text:'What is the opposite of transparent?',answer:'opaque',keywords:['opaque']},
{id:'xasq-32',text:'What do you call the bones that protect the brain?',answer:'skull',keywords:['skull','cranium']},
{id:'xasq-33',text:'What is the largest desert in the world?',answer:'Sahara',keywords:['sahara','antarctic']},
{id:'xasq-34',text:'How many years make up a millennium?',answer:'one thousand',keywords:['one thousand','thousand','1000']},
{id:'xasq-35',text:'What do you call a vehicle that travels in space?',answer:'spacecraft',keywords:['spacecraft','spaceship','rocket']},
{id:'xasq-36',text:'What is the main function of the kidney?',answer:'filter blood',keywords:['filter','blood','filtration']},
{id:'xasq-37',text:'What do you call a person who repairs water pipes?',answer:'plumber',keywords:['plumber']},
{id:'xasq-38',text:'What is the study of earthquakes called?',answer:'seismology',keywords:['seismology']},
{id:'xasq-39',text:'What do you call the top of a mountain?',answer:'summit',keywords:['summit','peak']},
{id:'xasq-40',text:'What is the capital of Germany?',answer:'Berlin',keywords:['berlin']},
{id:'xasq-41',text:'What do you call a drawing that shows the parts of something?',answer:'diagram',keywords:['diagram']},
{id:'xasq-42',text:'What is the opposite of rural?',answer:'urban',keywords:['urban']},
{id:'xasq-43',text:'What do you call a person who designs gardens?',answer:'landscape architect',keywords:['landscape','architect','gardener']},
{id:'xasq-44',text:'How many sides does a rectangle have?',answer:'four',keywords:['four','4']},
{id:'xasq-45',text:'What is the national animal of Australia?',answer:'kangaroo',keywords:['kangaroo']},
{id:'xasq-46',text:'What do you call someone who studies the weather?',answer:'meteorologist',keywords:['meteorologist']},
{id:'xasq-47',text:'What organ in the body produces insulin?',answer:'pancreas',keywords:['pancreas']},
{id:'xasq-48',text:'What is the chemical formula for table salt?',answer:'NaCl',keywords:['nacl','sodium chloride']},
{id:'xasq-49',text:'What do you call a piece of land surrounded by water?',answer:'island',keywords:['island']},
{id:'xasq-50',text:'What is the speed unit used for ships and aircraft?',answer:'knot',keywords:['knot','knots']},
{id:'xasq-51',text:'What do you call the person who serves food in a restaurant?',answer:'waiter',keywords:['waiter','server','waitress']},
{id:'xasq-52',text:'What planet is closest to Earth?',answer:'Venus',keywords:['venus']},
{id:'xasq-53',text:'What do you call a story written to be performed on stage?',answer:'play',keywords:['play','drama']},
{id:'xasq-54',text:'What is the main ingredient in chocolate?',answer:'cocoa',keywords:['cocoa','cacao']},
{id:'xasq-55',text:'What do you call the science of producing food by growing plants?',answer:'agriculture',keywords:['agriculture','farming']},
{id:'xasq-56',text:'What is the opposite of permanent?',answer:'temporary',keywords:['temporary']},
{id:'xasq-57',text:'What do you call water that falls from clouds?',answer:'rain',keywords:['rain','precipitation']},
{id:'xasq-58',text:'What is the currency of India?',answer:'rupee',keywords:['rupee']},
{id:'xasq-59',text:'What do you call a group of birds flying together?',answer:'flock',keywords:['flock']},
{id:'xasq-60',text:'What is the deepest ocean in the world?',answer:'Pacific',keywords:['pacific']},
{id:'xasq-61',text:'What do you call someone who cannot hear?',answer:'deaf',keywords:['deaf']},
{id:'xasq-62',text:'What is the largest bone in the human body?',answer:'femur',keywords:['femur','thigh bone']},
{id:'xasq-63',text:'What do you call a period of ten years?',answer:'decade',keywords:['decade']},
{id:'xasq-64',text:'In which direction does the sun rise?',answer:'east',keywords:['east']},
{id:'xasq-65',text:'What do you call a person who makes bread?',answer:'baker',keywords:['baker']},
{id:'xasq-66',text:'What is the capital of South Korea?',answer:'Seoul',keywords:['seoul']},
{id:'xasq-67',text:'What do you call the layer of gas that surrounds the Earth?',answer:'atmosphere',keywords:['atmosphere']},
{id:'xasq-68',text:'How many degrees are in a right angle?',answer:'ninety',keywords:['ninety','90']},
{id:'xasq-69',text:'What do you call the person who controls a court case?',answer:'judge',keywords:['judge']},
{id:'xasq-70',text:'What is the smallest continent?',answer:'Australia',keywords:['australia','oceania']},
{id:'xasq-71',text:'What do you call a person who puts out fires?',answer:'firefighter',keywords:['firefighter','fireman']},
{id:'xasq-72',text:'What is the gas that makes up most of the sun?',answer:'hydrogen',keywords:['hydrogen']},
{id:'xasq-73',text:'What do you call a line that goes around a circle?',answer:'circumference',keywords:['circumference']},
{id:'xasq-74',text:'How many teeth does a normal adult have?',answer:'thirty-two',keywords:['thirty-two','32']},
{id:'xasq-75',text:'What do you call the study of ancient human cultures?',answer:'archaeology',keywords:['archaeology','archeology']},
{id:'xasq-76',text:'What is the capital of Spain?',answer:'Madrid',keywords:['madrid']},
{id:'xasq-77',text:'What do you call a word that means the same as another word?',answer:'synonym',keywords:['synonym']},
{id:'xasq-78',text:'What is the opposite of drought?',answer:'flood',keywords:['flood']},
{id:'xasq-79',text:'What do you call the person who delivers babies?',answer:'midwife',keywords:['midwife','obstetrician']},
{id:'xasq-80',text:'What is the largest planet in our solar system?',answer:'Jupiter',keywords:['jupiter']},
{id:'xasq-81',text:'What do you call the practice of growing plants in water without soil?',answer:'hydroponics',keywords:['hydroponics']},
{id:'xasq-82',text:'What is the chemical symbol for sodium?',answer:'Na',keywords:['na','sodium']},
{id:'xasq-83',text:'What do you call the backbone of an animal?',answer:'spine',keywords:['spine','vertebral column','backbone']},
{id:'xasq-84',text:'What is the currency of China?',answer:'yuan',keywords:['yuan','renminbi']},
{id:'xasq-85',text:'What do you call someone who studies the past?',answer:'historian',keywords:['historian']},
{id:'xasq-86',text:'What is the largest internal organ?',answer:'liver',keywords:['liver']},
{id:'xasq-87',text:'What do you call the art of beautiful handwriting?',answer:'calligraphy',keywords:['calligraphy']},
{id:'xasq-88',text:'What is the opposite of horizontal?',answer:'vertical',keywords:['vertical']},
{id:'xasq-89',text:'What do you call a word that means the opposite of another?',answer:'antonym',keywords:['antonym']},
{id:'xasq-90',text:'What is the capital of Italy?',answer:'Rome',keywords:['rome']},
{id:'xasq-91',text:'What do you call the line where the sky appears to meet the land?',answer:'horizon',keywords:['horizon']},
{id:'xasq-92',text:'How many chambers does a human heart have?',answer:'four',keywords:['four','4']},
{id:'xasq-93',text:'What do you call someone who studies birds?',answer:'ornithologist',keywords:['ornithologist']},
{id:'xasq-94',text:'What is the main gas that plants absorb from the air?',answer:'carbon dioxide',keywords:['carbon dioxide','co2']},
{id:'xasq-95',text:'What do you call the colored part of the eye?',answer:'iris',keywords:['iris']},
{id:'xasq-96',text:'What is the largest island in the world?',answer:'Greenland',keywords:['greenland']},
{id:'xasq-97',text:'What do you call the area of land between hills or mountains?',answer:'valley',keywords:['valley']},
{id:'xasq-98',text:'What is the study of numbers and equations called?',answer:'mathematics',keywords:['mathematics','math','maths']},
{id:'xasq-99',text:'What do you call a flat image of the Earth\'s surface?',answer:'map',keywords:['map']},
{id:'xasq-100',text:'What is the hardest natural substance?',answer:'diamond',keywords:['diamond']},
{id:'xasq-101',text:'What do you call a sudden shaking of the ground?',answer:'earthquake',keywords:['earthquake']},
{id:'xasq-102',text:'What is the center of an atom called?',answer:'nucleus',keywords:['nucleus']},
{id:'xasq-103',text:'What do you call someone who fixes teeth?',answer:'dentist',keywords:['dentist']},
{id:'xasq-104',text:'What is the capital of Egypt?',answer:'Cairo',keywords:['cairo']},
{id:'xasq-105',text:'What do you call a young horse?',answer:'foal',keywords:['foal','colt']},
{id:'xasq-106',text:'What is the opposite of shallow?',answer:'deep',keywords:['deep']},
{id:'xasq-107',text:'What do you call someone who prepares food in a restaurant?',answer:'chef',keywords:['chef','cook']},
{id:'xasq-108',text:'What is the nearest star to Earth?',answer:'sun',keywords:['sun']},
{id:'xasq-109',text:'What do you call a device used to view very small objects?',answer:'microscope',keywords:['microscope']},
{id:'xasq-110',text:'What is the currency of the European Union?',answer:'euro',keywords:['euro']},
{id:'xasq-111',text:'What animal is the fastest on land?',answer:'cheetah',keywords:['cheetah']},
{id:'xasq-112',text:'What do you call the study of the structure of the body?',answer:'anatomy',keywords:['anatomy']},
{id:'xasq-113',text:'What is the opposite of export?',answer:'import',keywords:['import']},
{id:'xasq-114',text:'What do you call a body of water surrounded by land?',answer:'lake',keywords:['lake']},
{id:'xasq-115',text:'How many days are there in February during a non-leap year?',answer:'twenty-eight',keywords:['twenty-eight','28']},
{id:'xasq-116',text:'What do you call someone who makes furniture from wood?',answer:'carpenter',keywords:['carpenter']},
{id:'xasq-117',text:'What is the third planet from the sun?',answer:'Earth',keywords:['earth']},
{id:'xasq-118',text:'What do you call a severe shortage of food in a region?',answer:'famine',keywords:['famine']},
{id:'xasq-119',text:'What is the capital of Brazil?',answer:'Brasilia',keywords:['brasilia']},
{id:'xasq-120',text:'What do you call a type of animal that lives both in water and on land?',answer:'amphibian',keywords:['amphibian']},
{id:'xasq-121',text:'What is the opposite of guilty?',answer:'innocent',keywords:['innocent']},
{id:'xasq-122',text:'What do you call a person who works in a laboratory?',answer:'scientist',keywords:['scientist','lab technician','researcher']},
{id:'xasq-123',text:'What is the capital of Russia?',answer:'Moscow',keywords:['moscow']},
{id:'xasq-124',text:'What do you call a piece of music written for an orchestra?',answer:'symphony',keywords:['symphony']},
{id:'xasq-125',text:'What do you call the person who defends someone in court?',answer:'lawyer',keywords:['lawyer','attorney','defense counsel']},
{id:'xasq-126',text:'What is the opposite of increase?',answer:'decrease',keywords:['decrease','reduce']},
{id:'xasq-127',text:'What do you call the study of drugs and their effects?',answer:'pharmacology',keywords:['pharmacology']},
{id:'xasq-128',text:'What is the capital of Mexico?',answer:'Mexico City',keywords:['mexico city']},
{id:'xasq-129',text:'What do you call a device that converts sunlight into electricity?',answer:'solar panel',keywords:['solar panel','photovoltaic']},
{id:'xasq-130',text:'What is the most spoken language in South America?',answer:'Spanish',keywords:['spanish','portuguese']},
],

'summarize-group-discussion': [
{id:'xsgd-1',speakers:[
  {name:'Speaker A',text:'I believe university education should focus more on practical skills rather than theoretical knowledge. Employers consistently say graduates lack real-world abilities.'},
  {name:'Speaker B',text:'I disagree. Universities exist to develop critical thinking and analytical skills. Vocational training is available elsewhere for those who want practical skills.'},
  {name:'Speaker C',text:'Perhaps we need a curriculum that integrates both. Students could benefit from academic rigor combined with internships and project-based learning.'},
  {name:'Speaker A',text:'That makes sense. A blended approach would satisfy both academic standards and industry requirements.'}],
  keywords:['university','education','practical','skills','theoretical','knowledge','employers','graduates','critical','thinking','analytical','vocational','training','curriculum','integrates','internships','project-based','blended','approach','academic','industry']},
{id:'xsgd-2',speakers:[
  {name:'Speaker A',text:'I think social media companies should be held responsible for the content posted on their platforms. They profit from user engagement regardless of whether that content is harmful.'},
  {name:'Speaker B',text:'That would effectively make them censors. Freedom of expression is a fundamental right, and policing millions of posts daily is practically impossible.'},
  {name:'Speaker C',text:'There is a middle ground. Platforms could invest more in AI moderation tools while also empowering users with better reporting mechanisms and content controls.'},
  {name:'Speaker B',text:'I agree that better tools are needed, but we should be careful about who decides what constitutes harmful content.'}],
  keywords:['social','media','companies','responsible','content','platforms','profit','engagement','harmful','censors','freedom','expression','fundamental','right','policing','impossible','AI','moderation','tools','users','reporting','mechanisms','controls','decides','harmful']},
{id:'xsgd-3',speakers:[
  {name:'Speaker A',text:'Public transportation should be free for all citizens. It would reduce traffic congestion, lower emissions, and help low-income families who spend a large proportion of their income on transport.'},
  {name:'Speaker B',text:'The idea sounds appealing but someone has to pay for it. Making it free would either mean higher taxes or reduced service quality as funding decreases.'},
  {name:'Speaker C',text:'Some cities have tried partial solutions, like free transport during off-peak hours or for specific groups like students and seniors. This targets those who need it most without the full financial burden.'},
  {name:'Speaker A',text:'That is a pragmatic approach. Starting with targeted subsidies could be a stepping stone toward broader accessibility.'}],
  keywords:['public','transportation','free','citizens','reduce','traffic','congestion','emissions','low-income','families','income','transport','taxes','service','quality','funding','partial','solutions','off-peak','students','seniors','targets','financial','burden','pragmatic','subsidies','accessibility']},
{id:'xsgd-4',speakers:[
  {name:'Speaker A',text:'Genetic engineering of humans should be permitted if it can eliminate serious hereditary diseases. We have a moral obligation to reduce suffering where possible.'},
  {name:'Speaker B',text:'I am deeply concerned about this. Where do we draw the line? Allowing genetic modification for diseases could lead to designer babies selected for intelligence or appearance.'},
  {name:'Speaker C',text:'I think strict regulation is the key. We should allow therapeutic applications while maintaining clear boundaries against enhancement modifications.'},
  {name:'Speaker A',text:'Regulation is important, but enforcement across different countries and cultures would be extremely challenging.'}],
  keywords:['genetic','engineering','humans','permitted','eliminate','serious','hereditary','diseases','moral','obligation','reduce','suffering','concerned','draw','line','modification','designer','babies','intelligence','appearance','strict','regulation','therapeutic','applications','boundaries','enhancement','enforcement','countries','cultures','challenging']},
{id:'xsgd-5',speakers:[
  {name:'Speaker A',text:'I strongly believe that the voting age should be lowered to sixteen. Young people are affected by political decisions and should have a voice in choosing their leaders.'},
  {name:'Speaker B',text:'Sixteen-year-olds may lack the life experience and political maturity needed to make informed voting decisions. The current age of eighteen seems appropriate.'},
  {name:'Speaker C',text:'Perhaps instead of lowering the voting age, we should improve civic education in schools to ensure that when young people do vote at eighteen, they are well-prepared.'},
  {name:'Speaker B',text:'That is something we can all agree on. Better civic education would benefit voters of all ages.'}],
  keywords:['voting','age','lowered','sixteen','young','people','affected','political','decisions','voice','leaders','life','experience','maturity','informed','current','eighteen','appropriate','civic','education','schools','ensure','prepared','benefit','voters']},
{id:'xsgd-6',speakers:[
  {name:'Speaker A',text:'Zoos should be abolished. Keeping animals in captivity for human entertainment is unethical, regardless of how well they are cared for.'},
  {name:'Speaker B',text:'Modern zoos play a crucial role in conservation and breeding programs for endangered species. Without them, some species would have already gone extinct.'},
  {name:'Speaker C',text:'I think we need to reform zoos rather than abolish them. Focus should be on conservation and education, not entertainment. Animals that cannot be released should have habitats that mimic their natural environments.'},
  {name:'Speaker A',text:'I accept that conservation is important, but I still believe wild sanctuaries are preferable to traditional zoos.'}],
  keywords:['zoos','abolished','keeping','animals','captivity','entertainment','unethical','modern','crucial','role','conservation','breeding','programs','endangered','species','extinct','reform','education','habitats','mimic','natural','environments','sanctuaries','preferable','traditional']},
],

'respond-to-situation': [
{id:'xrts-1',scenario:'You are a student who has accidentally plagiarized a section of your essay by forgetting to cite a source. Your professor has noticed and asked to meet with you. Explain the situation honestly and propose how to fix it.',
  audioText:'You accidentally plagiarized part of your essay by forgetting to cite a source. Your professor wants to meet.',
  keywords:['accidentally','plagiarized','forgot','cite','source','honest','apologize','unintentional','fix','rewrite','learn','mistake','academic','integrity']},
{id:'xrts-2',scenario:'You are a tenant and your landlord has informed you of a significant rent increase starting next month. You cannot afford this increase. Write to your landlord to negotiate a more reasonable amount.',
  audioText:'Your landlord has announced a significant rent increase you cannot afford. Negotiate with them.',
  keywords:['rent','increase','cannot','afford','negotiate','reasonable','tenant','landlord','budget','appreciate','consider','alternative','loyal','lease']},
{id:'xrts-3',scenario:'You work in a team and notice that a junior colleague is struggling with their workload. Offer to help them without making them feel inadequate.',
  audioText:'A junior colleague is struggling with their workload. Offer help without making them feel inadequate.',
  keywords:['colleague','struggling','workload','help','offer','support','noticed','busy','together','share','tasks','team','appreciate','manage']},
{id:'xrts-4',scenario:'You have been invited to a friend\'s wedding that is taking place overseas. However, you cannot attend due to work commitments. Explain this to your friend sensitively.',
  audioText:'You cannot attend a friend\'s overseas wedding due to work. Explain sensitively.',
  keywords:['wedding','cannot','attend','overseas','work','commitments','sorry','disappointed','celebrate','wish','congratulations','special','day','another','time']},
{id:'xrts-5',scenario:'You are a customer at a bank. You have noticed an unauthorized transaction on your account. Report this to the bank employee and ask for an investigation.',
  audioText:'Report an unauthorized transaction on your bank account and request an investigation.',
  keywords:['unauthorized','transaction','account','bank','report','investigation','noticed','charge','recognize','security','freeze','resolve','immediately','concerned']},
{id:'xrts-6',scenario:'You are a university student who wants to change your major from engineering to arts. Discuss this decision with your academic advisor, explaining your reasons.',
  audioText:'You want to change your major from engineering to arts. Discuss with your academic advisor.',
  keywords:['change','major','engineering','arts','advisor','reasons','passion','interest','career','decided','appreciate','guidance','courses','transition']},
{id:'xrts-7',scenario:'You are the manager of a small team. One of your team members has been consistently underperforming. Have a constructive conversation about their performance and offer support.',
  audioText:'A team member has been underperforming. Have a constructive conversation and offer support.',
  keywords:['performance','underperforming','constructive','support','noticed','concerned','help','discuss','improvement','training','goals','expectations','together','plan']},
{id:'xrts-8',scenario:'You have received a job offer from another company but you are happy at your current job. Ask your current manager for a salary review by highlighting your contributions.',
  audioText:'You received a job offer elsewhere. Ask your current manager for a salary review.',
  keywords:['job','offer','another','company','current','manager','salary','review','contributions','value','team','appreciate','opportunity','discuss','compensation']},
{id:'xrts-9',scenario:'You are traveling abroad and have lost your passport. Contact your country\'s embassy to report the loss and ask about the process for getting an emergency replacement.',
  audioText:'You lost your passport while traveling abroad. Contact the embassy for help.',
  keywords:['lost','passport','traveling','abroad','embassy','report','emergency','replacement','help','process','documents','identity','concerned','urgently']},
{id:'xrts-10',scenario:'You are at university and your group project partner is not pulling their weight. The deadline is approaching and you need to address this directly with them.',
  audioText:'Your group project partner is not contributing. The deadline is near. Address this directly.',
  keywords:['group','project','partner','contributing','deadline','approaching','address','directly','fair','share','work','concerned','together','complete','discuss']},
],

};

// Merge function - called by app.js during init
PTE.mergeBankVocab = function() {
  for (var type in PTE._bankVocab) {
    if (!PTE.Questions[type]) PTE.Questions[type] = [];
    var existing = {};
    PTE.Questions[type].forEach(function(q) { existing[q.id] = true; });
    PTE._bankVocab[type].forEach(function(q) {
      if (!existing[q.id]) PTE.Questions[type].push(q);
    });
  }
};
