/**
 * PTE Academic — Writing Module
 * 2 question types: Summarize Written Text (SWT) + Write Essay (WE)
 * Official scoring rubrics from Pearson 2025 Score Guide
 */

window.PTE = window.PTE || {};

PTE.WRITING_TYPES = {
  SUMMARIZE_WRITTEN_TEXT: {
    id: 'swt',
    name: 'Summarize Written Text',
    shortName: 'SWT',
    icon: '📝',
    color: '#0ea5e9',
    colorLight: '#e0f2fe',
    module: 'writing',
    description: 'Read a passage and write a one-sentence summary of 5-75 words.',
    examItems: '1-2 items',
    answerTime: 600,
    minWords: 5,
    maxWords: 75,
    hasText: true,
    scoring: ['content', 'form', 'grammar', 'vocabulary'],
    skillsAssessed: ['Writing', 'Reading'],
    maxScores: { content: 2, form: 2, grammar: 2, vocabulary: 2 },
    totalMax: 8,
    tips: [
      'Write ONE complete sentence only — multiple sentences score 0 for Form',
      'Aim for 25-50 words (sweet spot for scoring)',
      'Include the main idea and key supporting points',
      'Use complex sentence structures: "while", "although", "which", "thereby"',
      'Do NOT copy phrases directly from the passage — paraphrase',
      'Check for capital letter at start and full stop at end'
    ]
  },
  WRITE_ESSAY: {
    id: 'write-essay',
    name: 'Write Essay',
    shortName: 'WE',
    icon: '✍️',
    color: '#8b5cf6',
    colorLight: '#ede9fe',
    module: 'writing',
    description: 'Write a 200-300 word essay on a given topic.',
    examItems: '1-2 items',
    answerTime: 1200,
    minWords: 200,
    maxWords: 300,
    hasText: true,
    scoring: ['content', 'form', 'development', 'grammar', 'generalLinguistic', 'vocabulary', 'spelling'],
    skillsAssessed: ['Writing'],
    maxScores: { content: 3, form: 2, development: 2, grammar: 2, generalLinguistic: 2, vocabulary: 2, spelling: 2 },
    totalMax: 15,
    tips: [
      'Structure: Introduction (thesis) → Body 1 → Body 2 → Conclusion',
      'Aim for 250-280 words — under 200 or over 300 loses Form marks',
      'Each body paragraph needs a topic sentence + example/evidence',
      'Use varied linking words: "Furthermore", "Conversely", "Nevertheless"',
      'Avoid repetition — use synonyms and varied sentence structures',
      'Leave 2 minutes to proofread for spelling and grammar errors'
    ]
  }
};

PTE.WritingQuestions = {
  'swt': [
    { id:'swt-1',
      title:'Climate Change and Agriculture',
      passage:'Climate change poses a significant threat to global agriculture. Rising temperatures, altered precipitation patterns, and increased frequency of extreme weather events are already affecting crop yields in many regions. Studies indicate that for every degree Celsius of warming, global wheat production could decline by six percent, rice by three point two percent, and maize by seven point four percent. Developing countries in tropical regions are particularly vulnerable, as they rely heavily on rain-fed agriculture and have limited resources for adaptation. However, some regions in higher latitudes may experience temporary benefits from longer growing seasons. Adaptation strategies include developing drought-resistant crop varieties, improving irrigation efficiency, and diversifying food sources. International cooperation and knowledge sharing are essential for building resilient agricultural systems that can withstand the challenges posed by a changing climate.',
      keywords:['climate','change','agriculture','temperatures','crop','yields','decline','developing','countries','vulnerable','adaptation','strategies','drought-resistant','irrigation','cooperation','resilient'] },
    { id:'swt-2',
      title:'The Rise of Remote Work',
      passage:'The COVID-19 pandemic accelerated a transformation in the way people work, making remote work a mainstream practice rather than a niche arrangement. Before the pandemic, only about five percent of full-time employees worked from home. By 2023, this figure had risen to approximately thirty percent in developed economies. Research from Stanford University found that remote workers are thirteen percent more productive than their office-based counterparts, partly due to fewer distractions and the elimination of commuting time. However, remote work also presents challenges, including social isolation, difficulty in maintaining work-life boundaries, and reduced opportunities for spontaneous collaboration. Many organizations have adopted hybrid models that combine remote and in-office work, attempting to capture the benefits of both arrangements. The long-term implications for urban planning, commercial real estate, and employee well-being continue to unfold.',
      keywords:['pandemic','remote','work','mainstream','productive','challenges','isolation','boundaries','collaboration','hybrid','models','urban','planning','well-being'] },
    { id:'swt-3',
      title:'Ocean Plastic Pollution',
      passage:'Plastic pollution in the world\'s oceans has reached alarming levels, with an estimated eight million metric tons of plastic entering marine environments annually. This waste originates from both land-based and ocean-based sources, including inadequate waste management systems, littering, and the fishing industry. Once in the ocean, plastic breaks down into microplastics — fragments smaller than five millimeters — which are ingested by marine organisms at every level of the food chain, from plankton to whales. Recent studies have detected microplastics in human blood, breast milk, and lung tissue, raising serious concerns about potential health effects. Governments worldwide are implementing measures such as banning single-use plastics, investing in recycling infrastructure, and supporting cleanup initiatives. However, experts argue that preventing plastic from entering the ocean in the first place is far more effective and cost-efficient than removal efforts.',
      keywords:['plastic','pollution','oceans','metric','tons','marine','microplastics','organisms','food','chain','health','effects','banning','single-use','recycling','prevention'] },
    { id:'swt-4',
      title:'Artificial Intelligence in Healthcare',
      passage:'Artificial intelligence is revolutionizing healthcare delivery across multiple domains, from diagnosis and treatment planning to drug discovery and administrative operations. Machine learning algorithms can now analyze medical images such as X-rays, CT scans, and pathology slides with accuracy that matches or exceeds that of experienced clinicians. In drug development, AI has reduced the time required to identify promising compounds from years to months, potentially accelerating the availability of new treatments. Natural language processing systems are being deployed to extract insights from electronic health records, enabling more personalized treatment recommendations. Despite these advances, significant challenges remain, including ensuring algorithmic fairness across diverse patient populations, maintaining data privacy, addressing liability concerns, and integrating AI tools into existing clinical workflows without disrupting the patient-physician relationship that remains central to quality care.',
      keywords:['artificial','intelligence','healthcare','diagnosis','treatment','machine','learning','medical','images','drug','discovery','natural','language','processing','personalized','challenges','fairness','privacy','liability','clinical'] },
    { id:'swt-5',
      title:'Urban Green Spaces',
      passage:'Urban green spaces, including parks, gardens, and urban forests, provide numerous benefits for city residents and the environment. Research has consistently demonstrated that access to green spaces improves mental health, reduces stress, and encourages physical activity. A study published in The Lancet found that people living within three hundred meters of green space had significantly lower rates of depression and anxiety. Environmentally, urban vegetation helps mitigate the heat island effect, improves air quality by filtering pollutants, and supports biodiversity by providing habitats for birds, insects, and other wildlife. Green spaces also contribute to social cohesion by offering communal areas where residents can interact, exercise, and participate in community activities. Despite these well-documented benefits, many cities, particularly in developing nations, face challenges in creating and maintaining adequate green spaces due to rapid urbanization, competing land-use demands, and limited municipal budgets.',
      keywords:['urban','green','spaces','parks','mental','health','stress','physical','activity','depression','heat','island','air','quality','biodiversity','social','cohesion','urbanization','budgets'] },
    { id:'swt-6',
      title:'The Gig Economy',
      passage:'The gig economy, characterized by short-term contracts and freelance work as opposed to permanent employment, has expanded dramatically over the past decade. Platforms such as Uber, Deliveroo, and Upwork have created millions of flexible work opportunities worldwide. Proponents argue that gig work offers freedom, autonomy, and the ability to balance multiple income streams. However, critics highlight that gig workers often lack access to traditional employment benefits including health insurance, paid leave, retirement contributions, and job security. The classification of gig workers as independent contractors rather than employees has become a contentious legal issue in many jurisdictions. Several countries, including Spain and the United Kingdom, have introduced legislation to provide gig workers with enhanced protections and minimum wage guarantees, while others continue to debate the appropriate regulatory framework for this evolving sector of the labor market.',
      keywords:['gig','economy','short-term','freelance','platforms','flexible','freedom','autonomy','benefits','health','insurance','job','security','independent','contractors','legislation','protections','regulatory'] },
    { id:'swt-7',
      title:'Sleep and Academic Performance',
      passage:'Research consistently demonstrates a strong correlation between sleep quality and academic performance among students of all ages. The National Sleep Foundation recommends that teenagers get eight to ten hours of sleep per night, yet studies indicate that over seventy percent of high school students regularly sleep less than the recommended amount. Sleep deprivation impairs cognitive functions essential for learning, including memory consolidation, attention, problem-solving, and creative thinking. A landmark study by the University of Minnesota found that when school start times were delayed by just one hour, students\' grades improved by an average of half a letter grade, and attendance rates increased. Despite this evidence, many educational institutions resist changing school schedules due to logistical challenges involving transportation, extracurricular activities, and parental work schedules. Some schools have instead implemented sleep education programs to teach students about the importance of healthy sleep habits.',
      keywords:['sleep','academic','performance','students','recommended','deprivation','cognitive','memory','attention','school','start','times','grades','attendance','education','healthy','habits'] },
    { id:'swt-8',
      title:'Renewable Energy Transition',
      passage:'The global transition from fossil fuels to renewable energy sources is accelerating, driven by declining costs, technological improvements, and growing urgency to address climate change. Solar photovoltaic costs have fallen by approximately ninety percent since 2010, making solar energy competitive with or cheaper than coal and natural gas in most markets. Wind energy has experienced similar cost reductions, with offshore wind emerging as a particularly promising technology. However, the intermittent nature of solar and wind power presents significant challenges for grid stability, requiring investment in energy storage technologies such as lithium-ion batteries, pumped hydro storage, and green hydrogen. The transition also raises important questions about energy equity, as developing nations may lack the capital and infrastructure needed to adopt renewable technologies at scale. Additionally, the mining of minerals essential for renewable energy systems, such as lithium, cobalt, and rare earth elements, creates its own environmental and social concerns.',
      keywords:['renewable','energy','transition','fossil','fuels','solar','costs','declined','wind','intermittent','grid','storage','batteries','hydrogen','equity','developing','nations','mining','minerals','environmental'] },
    { id:'swt-9',
      title:'Digital Privacy',
      passage:'In the digital age, personal privacy has become an increasingly complex and contested issue. Technology companies collect vast amounts of user data through social media platforms, search engines, mobile applications, and connected devices, often with minimal transparency about how this information is used, shared, or sold. The European Union\'s General Data Protection Regulation, implemented in 2018, established comprehensive data protection rights for individuals, including the right to access, correct, and delete personal data. Other jurisdictions, including California and Brazil, have followed with similar legislation. Despite these regulatory efforts, many consumers remain unaware of the extent of data collection or feel powerless to control it. Emerging technologies such as artificial intelligence and facial recognition further complicate the privacy landscape by enabling surveillance capabilities that were previously unimaginable. Balancing the benefits of data-driven innovation with the fundamental right to privacy remains one of the defining challenges of the twenty-first century.',
      keywords:['digital','privacy','technology','companies','data','collection','transparency','GDPR','protection','rights','regulation','consumers','surveillance','facial','recognition','innovation','fundamental','right'] },
    { id:'swt-10',
      title:'Antibiotic Resistance',
      passage:'Antibiotic resistance has been identified by the World Health Organization as one of the greatest threats to global health, food security, and development. The overuse and misuse of antibiotics in human medicine and animal agriculture have accelerated the evolution of resistant bacteria, rendering many existing treatments ineffective. Each year, approximately seven hundred thousand people die from drug-resistant infections worldwide, and projections suggest this number could rise to ten million annually by 2050 if no action is taken. The development pipeline for new antibiotics has slowed dramatically, as pharmaceutical companies find limited financial incentive in producing drugs designed to be used sparingly. Addressing this crisis requires a multifaceted approach, including stricter regulation of antibiotic prescriptions, investment in rapid diagnostic tools, development of alternative therapies such as bacteriophages, and global surveillance systems to track resistance patterns. Public awareness campaigns about the dangers of unnecessary antibiotic use are also considered essential.',
      keywords:['antibiotic','resistance','WHO','global','health','overuse','misuse','bacteria','infections','drug-resistant','pharmaceutical','regulation','prescriptions','diagnostic','alternative','therapies','surveillance','awareness'] },
  ],
  'write-essay': [
    { id:'we-1',
      prompt:'Some people believe that the government should spend more money on education, while others think the money should be spent on healthcare. Discuss both views and give your opinion.',
      keywords:['education','healthcare','government','spending','budget','priority','investment','human','capital','prevention','workforce','economic','growth','quality','life'] },
    { id:'we-2',
      prompt:'In many countries, the gap between the rich and the poor is widening. What are the causes of this trend and what measures can be taken to address it?',
      keywords:['inequality','wealth','gap','rich','poor','causes','globalization','technology','education','taxation','social','mobility','minimum','wage','redistribution'] },
    { id:'we-3',
      prompt:'With the increasing use of technology in the workplace, some jobs will disappear while new ones will be created. Do you agree or disagree with this statement? Give reasons for your answer.',
      keywords:['technology','workplace','automation','jobs','disappear','created','artificial','intelligence','skills','retraining','education','economy','innovation','employment'] },
    { id:'we-4',
      prompt:'Some people think that international tourism has negative effects on local communities. To what extent do you agree or disagree?',
      keywords:['international','tourism','negative','effects','local','communities','culture','environment','economy','employment','overcrowding','pollution','heritage','preservation'] },
    { id:'we-5',
      prompt:'Climate change is the most pressing issue facing humanity today. To what extent do you agree with this statement? What actions should individuals and governments take to address it?',
      keywords:['climate','change','pressing','issue','global','warming','emissions','renewable','energy','policy','individual','action','government','sustainability','future'] },
    { id:'we-6',
      prompt:'The advantages of living in a city outweigh the advantages of living in the countryside. Do you agree or disagree? Give specific reasons and examples.',
      keywords:['city','countryside','urban','rural','advantages','disadvantages','employment','opportunities','infrastructure','nature','cost','living','community','quality','life'] },
    { id:'we-7',
      prompt:'Some people believe that university education should be free for all students. Others argue that students should pay for their own education. Discuss both views and give your opinion.',
      keywords:['university','education','free','tuition','fees','students','government','funding','taxpayers','access','equality','investment','loans','quality','graduates'] },
    { id:'we-8',
      prompt:'In many societies, elderly people are no longer looked after by their families but are placed in care homes. What are the advantages and disadvantages of this trend?',
      keywords:['elderly','care','homes','families','aging','population','professional','healthcare','isolation','loneliness','cost','dignity','independence','cultural','values'] },
    { id:'we-9',
      prompt:'Social media has had a significant impact on how people communicate and form relationships. Discuss the positive and negative effects of social media on society.',
      keywords:['social','media','communication','relationships','positive','negative','connectivity','misinformation','mental','health','privacy','community','activism','addiction'] },
    { id:'we-10',
      prompt:'Some people believe that the best way to reduce crime is to give longer prison sentences. Others, however, believe there are better alternative ways of reducing crime. Discuss both views and give your opinion.',
      keywords:['crime','prison','sentences','punishment','rehabilitation','deterrent','education','community','service','prevention','poverty','causes','justice','recidivism'] },
  ]
};
